// <auto-generated />
using BulkyBook.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulkyBook.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240725074217_ForiegnKeyImplimentation")]
    partial class ForiegnKeyImplimentation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulkyBook.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 21,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 22,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 23,
                            Name = "Horror"
                        });
                });

            modelBuilder.Entity("BulkyBook.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price1")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Billy Spark",
                            CategoryId = 1,
                            Description = "King is time, time is everything, you are bound to time, and time is eternal. Nothing else is true!",
                            ISBN = "SWD00785",
                            ListPrice = 99.0,
                            Price1 = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Title = "Fortune Of Time"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Maya Rivers",
                            CategoryId = 2,
                            Description = "In a world where choices echo through time, three lives intertwine, revealing their shared destiny.",
                            ISBN = "EOD12345",
                            ListPrice = 120.0,
                            Price1 = 110.0,
                            Price100 = 100.0,
                            Price50 = 105.0,
                            Title = "Echoes of Destiny"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Olivia Gray",
                            CategoryId = 6,
                            Description = "Amidst fog-shrouded secrets, a forbidden love blooms, threatening to unravel the town's hidden past.",
                            ISBN = "WIM67890",
                            ListPrice = 80.0,
                            Price1 = 75.0,
                            Price100 = 65.0,
                            Price50 = 70.0,
                            Title = "Whispers in the Mist"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Sebastian Stone",
                            CategoryId = 3,
                            Description = "Alchemy, betrayal, and ancient prophecies collide as an unlikely hero seeks the philosopher's stone.",
                            ISBN = "TAL45678",
                            ListPrice = 105.0,
                            Price1 = 95.0,
                            Price100 = 85.0,
                            Price50 = 90.0,
                            Title = "The Alchemist's Legacy"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Isabella Sands",
                            CategoryId = 4,
                            Description = "Lost artifacts, hidden maps, and a quest for serendipity lead a group of adventurers across deserts and time.",
                            ISBN = "SOS23456",
                            ListPrice = 70.0,
                            Price1 = 65.0,
                            Price100 = 55.0,
                            Price50 = 60.0,
                            Title = "Sands of Serendipity"
                        });
                });

            modelBuilder.Entity("BulkyBook.Models.Product", b =>
                {
                    b.HasOne("BulkyBook.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
